export enum ROLE_TYPE {
  USER_ADMIN = 'USER_ADMIN',
  DIR = 'DIR',
  SALES_MGR = 'SALES_MGR',
  SALES_EMP = 'SALES_EMP',
  CONTACT_MGR = 'CONTACT_MGR',
  CONTACT_EMP = 'CONTACT_EMP',
  USER_READ_ONLY = 'USER_READ_ONLY',
}
